### ISSUE TITLE
Error with opencv when compiling

### ISSUE THREAD

**Issue by towardthesea** [robotology/onthefly-recognition#10]
I got this error when compiling the module. I use `OpenCV2` in my system:
```
icub@iiticublap118:~/icub-workspace/onthefly-recognition/build $ make 
Copying /home/icub/icub-workspace/onthefly-recognition/app/LUA/onTheFlyRec_gaze.lua to /home/icub/icub-workspace/onthefly-recognition/build/bin/./
[  0%] Built target copy_lua_gaze_in_build
Copying /home/icub/icub-workspace/onthefly-recognition/app/LUA/onTheFlyRec_main.lua to /home/icub/icub-workspace/onthefly-recognition/build/bin/./
[  0%] Built target copy_lua_bin_in_build
Copying /home/icub/icub-workspace/onthefly-recognition/app/LUA/mobile/onTheFlyRec_main_mobile.lua to /home/icub/icub-workspace/onthefly-recognition/build/bin/./
[  0%] Built target copy_lua_bin_mb_in_build
[ 16%] Building CXX object managerOnTheFly/CMakeFiles/managerOnTheFly.dir/src/ManagerThread.cpp.o
In file included from /home/icub/icub-workspace/onthefly-recognition/managerOnTheFly/include/ManagerThread.h:55:0,
                 from /home/icub/icub-workspace/onthefly-recognition/managerOnTheFly/src/ManagerThread.cpp:18:
/home/icub/icub-workspace/onthefly-recognition/managerOnTheFly/include/CropperThread.h:38:31: fatal error: opencv2/imgproc.hpp: No such file or directory
compilation terminated.
managerOnTheFly/CMakeFiles/managerOnTheFly.dir/build.make:62: recipe for target 'managerOnTheFly/CMakeFiles/managerOnTheFly.dir/src/ManagerThread.cpp.o' failed
make[2]: *** [managerOnTheFly/CMakeFiles/managerOnTheFly.dir/src/ManagerThread.cpp.o] Error 1
CMakeFiles/Makefile2:250: recipe for target 'managerOnTheFly/CMakeFiles/managerOnTheFly.dir/all' failed
make[1]: *** [managerOnTheFly/CMakeFiles/managerOnTheFly.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```
@GiuliaP 
Cheers,
Phuong

**Comment by pattacini** [comment]
@towardthesea it's likely that you have to compile `opencv` manually, including `opencv_contrib` modules too.

cc @vtikha

**Comment by GiuliaP** [comment]
Is this related to this commit : 292862e8b8995eb21038493cda7409a1faf80210 ?
[That was applied in order to compile with OpenCV 3.0 ]

**Comment by towardthesea** [comment]
> Is this related to this commit : 292862e ?
> [That was applied in order to compile with OpenCV 3.0 ]

Maybe this detail should be mentioned in README :)

Thanks! I close this issue here!
